# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010A08)
$foreground = rgb(F5FFFD)
$color0 = rgb(111413)
$color1 = rgb(8F3232)
$color2 = rgb(3B5C3B)
$color3 = rgb(7A6322)
$color4 = rgb(28405C)
$color5 = rgb(46285C)
$color6 = rgb(346666)
$color7 = rgb(D1D1D1)
$color8 = rgb(212927)
$color9 = rgb(B84242)
$color10 = rgb(57A355)
$color11 = rgb(DBBB60)
$color12 = rgb(5183B8)
$color13 = rgb(935FB8)
$color14 = rgb(51B8B0)
$color15 = rgb(F5FFFD)
