# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F5FFFD
background         #010A08
cursor             #9DF5E2

active_tab_foreground     #010A08
active_tab_background     #F5FFFD
inactive_tab_foreground   #F5FFFD
inactive_tab_background   #010A08

active_border_color   #F5FFFD
inactive_border_color #010A08
bell_border_color     #8F3232

color0      #111413
color1		#8F3232
color2		#3B5C3B
color3		#7A6322
color4		#28405C
color5		#46285C
color6		#346666
color7		#D1D1D1
color8		#212927
color9		#B84242
color10		#57A355
color11		#DBBB60
color12		#5183B8
color13		#935FB8
color14		#51B8B0
color15		#F5FFFD
